
#-----------------------------------------------------------------------

APP       := Common
TARGET    := IPGeoServer
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += 
LIB       += 

INCLUDE   += -I../public

INCLUDE   += -I../../tools/LogManager
INCLUDE   += -I../../tools/DBManager
INCLUDE   += -I../../thirdparty/sql-builder


#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
