
#-----------------------------------------------------------------------

APP       := Common
TARGET    := IPGeoServerClient
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += 
LIB       += 

INCLUDE += -I../../public/
INCLUDE += -I../
#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
